//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Guide.rc
//
#define IDR_CNTR_INPLACE                6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_TREE_DELETESELECTED          101
#define IDP_FAILED_TO_CREATE            102
#define ID_TREE_INSERT                  102
#define IDR_MAINFRAME                   128
#define IDR_GuideTYPE                   129
#define IDC_FONTNAME                    129
#define IDB_BOOK                        129
#define IDC_FONTSIZE                    130
#define IDS_CONFIRM_DELETE              131
#define ID_FORMAT_LINESPACING           132
#define IDS_PRINT_ALL                   133
#define IDS_PRINT_ONLYSEL               134
#define IDS_PRINT_SELANDCHILDREN        135
#define IDR_FORMAT_BAR                  136
#define IDB_PAGE                        139
#define IDR_TREE_MENU                   140
#define IDI_TRAYICON                    141
#define IDR_TRAYMENU                    142
#define IDR_TREE_ACCEL                  143
#define IDD_HELP_KEYBOARD               144
#define IDR_NUMBER_MENU                 145
#define IDR_LINESPACING                 146
#define IDD_PREF_FONTS                  147
#define IDD_PREF_COLORS                 148
#define IDD_PREF_STARTUP                149
#define IDR_RMB                         150
#define IDD_SEARCH_DIALOG               151
#define IDD_PREF_PRINT                  152
#define IDI_JFY_LEFT                    154
#define IDI_JFY_CENTER                  155
#define IDI_JFY_RIGHT                   156
#define IDI_FMT_BOLD                    157
#define IDI_FMT_ITALIC                  158
#define IDI_FMT_UNDERLINE               159
#define IDD_PRINT_PREVIEW_BAR           161
#define IDD_CUSTOM_EXPORT               162
#define IDD_FGCOLOR                     163
#define IDC_NODROP                      164
#define IDR_DROP_MENU                   165
#define IDC_POINTER_COPY                166
#define IDD_DATEFMT                     168
#define IDD_HYPERLINK                   169
#define IDD_SELECTNODE                  170
#define IDB_NODE39                      211
#define IDB_ICONS                       211
#define IDB_NODE40                      212
#define IDB_STATE_ICONS                 215
#define IDC_LIST1                       1000
#define IDC_LIST2                       1001
#define IDC_RADIO_TREE_FONT_SYSDEFAULT  1001
#define IDC_SMATCHCASE                  1001
#define IDC_RADIO_TREE_FONT_USER        1002
#define IDC_TREE_FONT_CHOOSE            1003
#define IDC_RADIO_SHOW_EMPTY            1004
#define IDC_TREE_BACK                   1004
#define IDC_RADIO_TEXT_FONT_SYSDEFAULT  1004
#define IDC_RADIO_LOAD_LAST             1005
#define IDC_RADIO_TEXT_FONT_USER        1005
#define IDC_SONLYTITLES                 1005
#define IDC_RADIO_TEXT_COLOR_USER       1006
#define IDC_TEXT_FONT_CHOOSE            1006
#define IDC_SONLYSUBTREE                1006
#define IDC_RADIO_DATEFMT_SYSTEM        1006
#define IDC_TEXT_FORE                   1007
#define IDC_RADIO_DATEFMT_CUSTOM        1007
#define IDC_TEXT_BACK                   1008
#define IDC_RADIO_TREE_COLOR_SYSDEFAULT 1009
#define IDC_RADIO_TREE_COLOR_USER       1010
#define IDC_TREE_FORE                   1011
#define IDC_RADIO_TEXT_COLOR_SYSDEFAULT 1012
#define IDC_TREE_COLOR_SAMPLE           1013
#define IDC_TEXT_COLOR_SAMPLE           1014
#define IDC_SFIND                       1016
#define IDC_SCLOSE                      1017
#define IDC_SWHAT                       1018
#define IDC_SRESULT                     1019
#define IDC_PFXNUM                      1026
#define IDC_BEGINONNEW                  1027
#define IDC_RESETALL                    1028
#define IDC_HCOLOR                      1030
#define IDC_JUSLEFT                     1031
#define IDC_JUSCENTER                   1032
#define IDC_JUSRIGHT                    1033
#define IDC_HDGLIST                     1034
#define IDC_PFONTNAMES                  1035
#define IDC_PFONTSIZES                  1036
#define IDC_PFMTBOLD                    1037
#define IDC_PFMTITALIC                  1038
#define IDC_PFMTUNDERLINE               1039
#define IDC_PFONTNAMES2                 1040
#define IDC_ABT_HEADING                 1041
#define IDC_PFONTSIZES2                 1041
#define IDC_ABT_URL                     1042
#define IDC_PFMTBOLD2                   1042
#define IDC_ABT_EMAIL                   1043
#define IDC_PFMTITALIC2                 1043
#define IDC_PRINT_PREVIEW_WHAT          1044
#define IDC_PFMTUNDERLINE2              1044
#define IDC_ABT_URL2                    1044
#define IDC_ABT_EMAIL2                  1044
#define IDC_ABT_GUG                     1044
#define IDC_EXPORT_WHAT                 1045
#define IDC_PRINTDLG_ENTIRE_DOCUMENT    1046
#define IDC_PRINTDLG_ONLY_SELECTED      1047
#define IDC_PRINTDLG_SELANDCHILDREN     1048
#define IDC_SET_DATEFMT                 1049
#define IDC_RADIO_TIMEFMT_SYSTEM        1051
#define IDC_RADIO_TIMEFMT_CUSTOM        1052
#define IDC_SET_TIMEFMT                 1053
#define IDC_EDITFMT                     1054
#define IDC_EDITSAMPLE                  1055
#define IDC_BUTTON1                     1056
#define IDC_BUTTON2                     1057
#define IDC_CHECK1                      1058
#define IDC_BUTTON3                     1059
#define IDC_CHECK_ESC_MIN               1059
#define IDC_BUTTON4                     1060
#define IDC_CHECK_X_MIN                 1060
#define IDC_CHECK3                      1061
#define IDC_AUTOSAVE_MINUTES            1061
#define IDC_CHECK_BACKUP                1062
#define IDC_CHECK2                      1063
#define IDC_CHECK4                      1064
#define IDC_CHECK_SYSTRAY               1065
#define IDC_CHECK_SAVE_ON_CLOSE         1066
#define IDC_CHECK_SINGLECLICK           1067
#define IDC_CHECK_AUTOSAVE              1068
#define IDC_TEXT                        1069
#define IDC_NODE                        1072
#define IDC_CHOOSENODE                  1073
#define IDC_FILEDIR                     1074
#define IDC_CHOOSEFILE                  1075
#define IDC_EMAIL                       1076
#define IDC_CHOOSEDIR                   1078
#define IDC_URL                         1079
#define IDC_URLTEXT                     1080
#define IDC_EMAILTEXT                   1081
#define IDC_NODETEXT                    1082
#define IDC_FILEDIRTEXT                 1083
#define IDC_CLEARLINK                   1084
#define IDC_UPDATELINK                  1085
#define IDC_TREE                        1086
#define IDC_PMODE                       1090
#define IDC_RGY2INI                     1091
#define IDC_INI2RGY                     1092
#define IDC_CHECK_ICONS                 1093
#define IDC_CHECK_CBOXES                1094
#define IDD_PREF_DATEFMT                1539
#define IDD_TIMEFMT                     1540
#define IDD_PREF_FONTANDCOL             1541
#define IDD_PREF_PORTABLE               1542
#define IDC_FGCOLOR_AUTO                1900
#define IDC_FGCOLOR_MORE                1901
#define IDC_FGCOL1                      2000
#define IDC_FGCOL2                      2001
#define IDC_FGCOL3                      2002
#define IDC_FGCOL4                      2003
#define IDC_FGCOL5                      2004
#define IDC_FGCOL6                      2005
#define IDC_FGCOL7                      2006
#define IDC_FGCOL8                      2007
#define IDC_FGCOL9                      2008
#define IDC_FGCOL10                     2009
#define IDC_FGCOL11                     2010
#define IDC_FGCOL12                     2011
#define IDC_FGCOL13                     2012
#define IDC_FGCOL14                     2013
#define IDC_FGCOL15                     2014
#define IDC_FGCOL16                     2015
#define IDC_FGCOL17                     2016
#define IDC_FGCOL18                     2017
#define IDC_FGCOL19                     2018
#define IDC_FGCOL20                     2019
#define IDC_FGCOL21                     2020
#define IDC_FGCOL22                     2021
#define IDC_FGCOL23                     2022
#define IDC_FGCOL24                     2023
#define IDC_FGCOL25                     2024
#define IDC_FGCOL26                     2025
#define IDC_FGCOL27                     2026
#define IDC_FGCOL28                     2027
#define IDC_FGCOL29                     2028
#define IDC_FGCOL30                     2029
#define IDC_FGCOL31                     2030
#define IDC_FGCOL32                     2031
#define IDC_FGCOL33                     2032
#define IDC_FGCOL34                     2033
#define IDC_FGCOL35                     2034
#define IDC_FGCOL36                     2035
#define IDC_FGCOL37                     2036
#define IDC_FGCOL38                     2037
#define IDC_FGCOL39                     2038
#define IDC_FGCOL40                     2039
#define IDS_NO_PRINTERS                 2040
#define IDS_NOLAUNCH_URL                2041
#define IDS_UNKNOWN_URLTYPE             2042
#define IDS_FILE_WRITE_ERROR            2043
#define IDS_EXPORT_SUCCESS              2044
#define IDS_NODROP                      2045
#define IDS_NOBENEATH                   2046
#define IDS_FMT_DATESYS                 2047
#define IDS_FMT_DATECUS                 2048
#define IDS_FMT_TIMESYS                 2049
#define IDS_FMT_TIMECUS                 2050
#define IDS_NOBACKUP                    2051
#define IDS_FILELOCKED                  2052
#define IDS_FILEOPENERR                 2053
#define IDS_NOBLANKFORMAT               2054
#define IDS_NOGDE                       2055
#define IDS_NOLAUNCH_PAGE               2056
#define IDS_NOLINKTEXT                  2057
#define IDS_NONODE                      2058
#define IDS_NOFILEDIR                   2059
#define IDS_NOEMAIL                     2060
#define IDS_NOURL                       2061
#define IDS_NODQINEMAIL                 2062
#define IDS_NODQINURL                   2063
#define IDS_RGY2INI_CONFIRM             2064
#define IDS_STRING2065                  2065
#define IDS_INI2RGY_CONFIRM             2065
#define IDS_ON_NEXT_DOC                 2066
#define IDS_SAMPLETEXT                  2066
#define IDS_FMTFONT1                    2067
#define IDS_FMTFONT2                    2068
#define IDS_FMTFONT3                    2069
#define IDS_FMTFONT4                    2070
#define IDS_NORICHEDIT5DLL              2071
#define IDS_SBARFMT1                    2072
#define IDS_SBARFMT2                    2073
#define IDS_SBARFMT3                    2074
#define IDS_SBARFMT4                    2075
#define IDS_STRING2076                  2076
#define IDS_FILEEXPORT_FILT             2076
#define IDS_SEARCHCOL1                  2077
#define IDS_SEARCHCOL2                  2078
#define IDS_SEARCHCOL3                  2079
#define IDS_SEARCH_INTITLE              2080
#define IDS_HLINK_NOTGT                 2081
#define IDS_HDGFMT1                     2082
#define IDS_HDGFMT2                     2083
#define IDS_SELDIR                      2084
#define IDS_ALLFILES_FILT               2085
#define IDS_ICONWND_TITLE               2086
#define IDS_FORMATBAR_NAME              2087
#define IDS_PREFDLG_NAME                2088
#define IDS_CHILDCOUNT_0                2089
#define IDS_CHILDCOUNT_1                2090
#define IDS_CHILDCOUNT_MANY             2091
#define IDS_SEARCH_FOUNDINTITLE         2092
#define IDS_SEARCH_NOPAGES              2093
#define IDS_SEARCH_NOSTRING             2094
#define IDS_PAGE_NEWCHILD               2095
#define IDS_PAGE_NEWTOP                 2096
#define IDS_PAGENAME_NOEMPTY            2097
#define IDS_DRAG_SBAR1                  2098
#define IDS_DRAG_SBAR2                  2099
#define IDS_DRAG_SBAR3                  2100
#define IDS_DRAG_SBAR4                  2101
#define IDS_DRAG_SBAR5                  2102
#define IDS_DRAG_SBAR6                  2103
#define IDS_STRING2104                  2104
#define IDS_DRAG_SBAR7                  2104
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_FORMAT_BOLD                  32771
#define ID_FORMAT_ITALIC                32772
#define ID_FORMAT_UNDERLINE             32773
#define ID_FORMAT_LEFTJUSTIFIED         32774
#define ID_FORMAT_CENTERJUSTIFIED       32775
#define ID_FORMAT_RIGHTJUSTIFIED        32776
#define ID_INSERT_BULLET                32777
#define ID_FORMAT_NUMBERED              32777
#define ID_FORMAT_BACKGROUNDCOLOUR      32778
#define ID_FORMAT_FOREGROUNDCOLOUR      32780
#define ID_FORMAT_BULLETED              32781
#define ID_CHAR_BOLD                    32799
#define ID_CHAR_ITALIC                  32800
#define ID_CHAR_COLOR                   32801
#define ID_CHAR_UNDERLINE               32802
#define ID_PARA_LEFT                    32803
#define ID_PARA_CENTER                  32804
#define ID_PARA_RIGHT                   32805
#define ID_TREE_ADDCHILDPAGE            32806
#define ID_TREE_RENAMEPAGE              32807
#define ID_TREE_DELETEPAGE              32808
#define ID_TREE_ADDTOP                  32810
#define ID_VIEW_USESYSTEMTRAY           32812
#define ID_TRAY_RESTORE                 32815
#define ID_TRAY_EXIT                    32816
#define ID_TREE_ESCKEY                  32818
#define ID_TREE_MOVEUP                  32820
#define ID_TREE_SHIFTFOCUS              32822
#define ID_TREE_MOVEDOWN                32823
#define ID_TREE_INSERTAFTER             32829
#define ID_POPUP_ADDPAGEBELOW           32834
#define ID_TREE_ADDPAGEABOVE            32835
#define ID_TREE_ADDPAGEBELOW            32836
#define ID_POPUP_ADDPAGEABOVE           32837
#define ID_RMB_ADDPAGEABOVE             32839
#define ID_RMB_ADDPAGEBELOW             32840
#define ID_HELP_KEYBOARDSHORTCUTS       32841
#define ID_FMTNUM_LOWER_ROMAN           32849
#define ID_FMTNUM_UPPER_ROMAN           32850
#define ID_FMTNUM_LOWER_ALPHA           32851
#define ID_FMTNUM_UPPER_ALPHA           32852
#define ID_FMTNUM_ARABIC                32853
#define ID_FORMAT_LINESPC_ONEHALF       32859
#define ID_FORMAT_LINESPC_TWO           32860
#define ID_FORMAT_LINESPC_ONE           32861
#define ID_VIEW_PREFERENCES             32862
#define ID_FORMAT_STRIKETHROUGH         32863
#define ID_FORMAT_HYPERLINK             32870
#define ID_TREE_SEARCH                  32879
#define ID_RMB_SEARCH                   32883
#define ID_RMB_MOVEUP                   32892
#define ID_RMB_MOVEDOWN                 32893
#define ID_RMB_ADDTOP                   32894
#define ID_RMB_ADDCHILD                 32895
#define ID_RMB_RENAME                   32896
#define ID_RMB_DELETE                   32897
#define ID_FORMAT_DECINDENT             32898
#define ID_FORMAT_INCINDENT             32899
#define ID_FILE_EXPORT                  32907
#define ID_FILE_RECENTFILES             32911
#define ID_FILE_PRINTSUBTREE            32917
#define ID_FILE_PRINTPREVIEWSUBTREE     32918
#define ID_FILE_EXPORTSUBTREE           32919
#define ID_RMB_PRINTSUBTREE             32922
#define ID_RMB_PRINTPREVIEWSUBTREE      32923
#define ID_RMB_EXPORTSUBTREE            32924
#define ID_PRINT_ENTIREDOCUMENT         32929
#define ID_PRINT_ONLYSELECTEDPAGE       32930
#define ID_PRINT_SELECTEDPAGEANDCHILDREN 32931
#define ID_RMB_PRINT                    32933
#define ID_POPUP_PRINTPREVIEW           32934
#define ID_RMB_PRINTPREVIEW             32935
#define ID_DROP_COPY                    32938
#define ID_DROP_MOVE                    32939
#define ID_TREE_EXPANDALL               32944
#define ID_TREE_COLLAPSEALL             32945
#define ID_EDIT_INSERTDATE              32947
#define ID_EDIT_INSERTTIME              32950
#define ID_RMB_COLOR                    32958
#define ID_RMB_BGCOLOR                  32959
#define ID_EDIT_PASTEASTEXT             32960
#define ID_RMB_NODEICON                 32964
#define ID_TREE_COLOR                   32965
#define ID_TREE_BGCOLOR                 32966
#define ID_TREE_NODEICON                32967
#define ID_INDICATOR_CHILDCOUNT         59142
#define ID_INDICATOR_LC                 59143
#define ID_VIEW_FORMATBAR               59396

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        216
#define _APS_NEXT_COMMAND_VALUE         32968
#define _APS_NEXT_CONTROL_VALUE         1095
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
